from datetime import date
from enum import Enum
from pathlib import Path
from typing import Callable, Optional, cast, Generic
from ophyd_async.core import (
    FilenameProvider,
    PathProvider,
    PathInfo,
    UUIDFilenameProvider,
)
import uuid
import os
from typing import TypeVar


class YMDGranularity(int, Enum):
    """Enum for specifying the granularity of the year/month/day portion of the path generated by NSLS2PathProvider.

    Attributes
    ----------
    none : int
        No granularity, do not include year/month/day in the path.
    year : int
        Include only the year in the path.
    month : int
        Include the year and month in the path.
    day : int
        Include the year, month, and day in the path.
    """

    none = 0
    year = 1
    month = 2
    day = 3


AcqModeT = TypeVar("AcqModeT", bound=Enum)


class AcqModeFilenameProvider(UUIDFilenameProvider, Generic[AcqModeT]):
    """Filename provider that includes acquisition mode in the filename.

    Parameters
    ----------
    mode_type : type[AcqModeT]
        The type of the acquisition mode. Must be a string enum.
    initial_mode : AcqModeT, optional
        The initial acquisition mode. If not provided, the first option in the mode_type enum will be used.
    include_datakey_name : bool, default False
        Whether to include the datakey name in the filename. If True, the datakey name will be prefixed to the filename.
    uuid_call_func : Callable, default uuid.uuid4
        The function to call to generate the UUID portion of the filename. Defaults to uuid.uuid4.
    uuid_call_args : list, optional
        The arguments to pass to the uuid_call_func when generating the UUID. Defaults to None.
    """

    def __init__(
        self,
        mode_type: type[AcqModeT],
        initial_mode: Optional[AcqModeT] = None,
        include_datakey_name: bool = False,
        uuid_call_func: Callable = uuid.uuid4,
        uuid_call_args: Optional[list] = None,
    ):
        if not isinstance(mode_type, type) or not issubclass(mode_type, Enum):
            raise TypeError("Acquisition mode type must be a subclass of Enum!")

        if len(mode_type) == 0:
            raise ValueError("Acquisition mode enum must have at least one option!")

        if initial_mode is not None and not isinstance(initial_mode, mode_type):
            raise ValueError(
                f"Initial acquisition mode {initial_mode} is not a valid option for {mode_type}!"
            )

        self._mode = initial_mode
        if initial_mode is None:
            self._mode = list(mode_type)[0]
        else:
            self._mode = initial_mode

        self._mode_type = mode_type
        self._include_datakey_name = include_datakey_name
        super().__init__(uuid_call_func=uuid_call_func, uuid_call_args=uuid_call_args)

    def switch_mode(self, new_mode: AcqModeT):
        """Switches the acquisition mode to a new mode.

        Parameters
        ----------
        new_mode : AcqModeT
            The new acquisition mode to switch to. Must be a member of the mode_type enum provided at initialization.

        Raises
        ------
        ValueError
            If the new_mode is not a valid option for the mode_type enum.
        """

        if not isinstance(new_mode, self._mode_type):
            raise ValueError(f"{new_mode} is not a valid option for {self._mode_type}!")
        self._mode = new_mode

    def __call__(self, datakey_name: Optional[str] = None) -> str:
        """Generates a filename that includes the current acquisition mode and optionally the datakey name.

        Parameters
        ----------
        datakey_name : str, optional
            The name of the datakey to include in the filename. Only used if include_datakey_name is True.

        Returns
        -------
        str
            The generated filename.

        """

        filename = super().__call__(datakey_name=cast(AcqModeT, self._mode).value)
        if self._mode is not None:
            filename = f"{self._mode.value}_{filename}"
        if self._include_datakey_name and datakey_name is not None:
            filename = f"{datakey_name}_{filename}"
        return filename


class NSLS2PathProvider(PathProvider):
    """Default NSLS2 path provider.

    Generates paths in the following format:

    /nsls2/data/{TLA}/proposals/{CYCLE}/{PROPOSAL}/assets/{DETECTOR}/{Y}/{M}/{D}

    If include_scan_id_dir is provided, an additional directory will be created at the
    end of the path with the name scan_{scan_id:06}.

    Parameters
    ----------
    metadata_dict : dict
        Typically `RE.md`. Used for dynamic save path generation from sync-d experiment
    filename_provider : FilenameProvider, default UUIDFilenameProvider()
        Filename provider to use for generating filenames.
    beamline_tla : str, optional
        TLA of the beamline to use in the path. If not provided, the TLA will be determined from
        the ENDSTATION_ACRONYM or BEAMLINE_ACRONYM environment variables.
    beamline_tla_suffix : str, optional
        Suffix to add to TLA when generating path.
    separator : str, default os.path.sep
        Separator to use in YMD portion of the path. Defaults to os.path.sep. Should be set to `\\` for Windows paths.
    granularity : YMDGranularity, default YMDGranularity.day
        Granularity of the YMD portion of the path. If set to YMDGranularity.day, the path will include year, month,
        and day directories. If set to YMDGranularity.month, the path will include year and month directories.
        If set to YMDGranularity.year, the path will include only the year directory.
    include_scan_id_dir : bool, default False
        Whether to include a scan ID directory at the end of the path.
    """

    def __init__(
        self,
        metadata_dict: dict,
        filename_provider: FilenameProvider = UUIDFilenameProvider(),
        granularity: YMDGranularity = YMDGranularity.day,
        separator=os.path.sep,
        beamline_tla: Optional[str] = None,
        beamline_tla_suffix: Optional[str] = None,
        include_scan_id_dir: bool = False,
    ):
        self._filename_provider = filename_provider
        self._metadata_dict = metadata_dict
        self._granularity = granularity
        self._ymd_separator = separator

        beamline_data_dir = (
            beamline_tla
            if beamline_tla is not None
            else os.getenv(
                "ENDSTATION_ACRONYM", os.getenv("BEAMLINE_ACRONYM", "")
            ).lower()
        ) + (beamline_tla_suffix or "")

        self._beamline_proposals_dir = (
            Path("/nsls2/data/") / beamline_data_dir / "proposals"
        )

        self._include_scan_id_dir = include_scan_id_dir

    @property
    def filename_provider(self) -> FilenameProvider:
        """Returns the filename provider used by this path provider."""

        return self._filename_provider

    def generate_directory_path(self, datakey_name) -> Path:
        """Helper function that generates ymd path structure.

        Depending on the granularity, the path will include year, month, and day directories.
        If the include_scan_id_dir is provided, an additional directory will be created at the end of the
        path with the name scan_{scan_id:06}.

        Parameters
        ----------
        datakey_name : str
            The name of the datakey to include in the path.
            If provided, the datakey name will be used as a prefix to the YMD portion of the path.

        Returns
        -------
        Path
            The generated directory path.

        Raises
        ------
        KeyError
            If the metadata dictionary does not contain the required keys 'cycle' and 'data_session'.
        """

        current_date_template = ""
        if self._granularity >= YMDGranularity.day:
            current_date_template = f"%Y{self._ymd_separator}%m{self._ymd_separator}%d"
        elif self._granularity == YMDGranularity.month:
            current_date_template = f"%Y{self._ymd_separator}%m"
        elif self._granularity == YMDGranularity.year:
            current_date_template = f"%Y{self._ymd_separator}"

        current_date = Path(date.today().strftime(current_date_template))

        if datakey_name is None:
            ymd_dir_path = current_date
        else:
            ymd_dir_path = Path(datakey_name) / current_date

        if (
            "cycle" not in self._metadata_dict
            or "data_session" not in self._metadata_dict
        ):
            raise KeyError(
                "Metadata dictionary must contain 'cycle' and 'data_session' keys!"
            )

        directory_path = (
            self._beamline_proposals_dir
            / self._metadata_dict["cycle"]
            / self._metadata_dict["data_session"]
            / "assets"
            / ymd_dir_path
        )

        if self._include_scan_id_dir:
            directory_path = (
                directory_path / f"scan_{self._metadata_dict['scan_id']:06}"
            )

        return directory_path

    def __call__(self, datakey_name) -> PathInfo:
        """Generates a PathInfo object containing the directory path and filename for the current acquisition.

        Parameters
        ----------
        datakey_name : str
            The name of the datakey to include in the path.

        Returns
        -------
        PathInfo
            The generated PathInfo object.
        """

        directory_path = self.generate_directory_path(datakey_name)

        return PathInfo(
            directory_path=directory_path,
            filename=self._filename_provider(),
            create_dir_depth=-self._granularity
            - (1 if self._include_scan_id_dir else 0),
        )
